Repository pixelfed/pixelfed, pull requests merged in 2018-08, with the labels that each got.

#341 Add MAIL_FROM_ADDRESS and MAIL_FROM_NAME to env
  .env.example
Labels: deployment

#331 Provide at least a major version of redis for the docker image
  docker-compose.yml
Labels: deployment

#259 Added the law requirements for the EU/EEA
  resources/views/site/privacy.blade.php
Labels: legal

#296 update galician
  resources/lang/gl/navmenu.php
  resources/lang/vendor/backup/gl/notifications.php
Labels: internationalization, localization

#303 s/instagram/Instagram/
  README.md
Labels: typo, ui

#305 i18n: Update Polish translation
  resources/lang/pl/navmenu.php
  resources/lang/pl/notification.php
Labels: internationalization, localization

#306 [i18n] Update Occitan translation
  resources/lang/oc/navmenu.php
  resources/lang/oc/notification.php
  resources/lang/oc/profile.php
  resources/lang/oc/timeline.php
Labels: internationalization, localization

#310 French Translate update
  resources/lang/fr/navmenu.php
  resources/lang/fr/notification.php
Labels: internationalization, localization

#275 Make mobile view profile more compact
  resources/assets/sass/custom.scss
  resources/views/profile/show.blade.php
Labels: ui

#294 Adapt profile changes to discover
  resources/views/discover/home.blade.php
  resources/views/discover/tags/show.blade.php
Labels: ui

#314 Make followers list flush on mobile
  resources/views/profile/followers.blade.php
  resources/views/profile/following.blade.php
Labels: ui

#384 Update (empty post)
  resources/lang/oc/profile.php
Labels: internationalization

#281 Create an Apache based Docker image ready for production
  .dockerignore
  Dockerfile
  config/trustedproxy.php
  contrib/docker/Dockerfile.apache
  contrib/docker/Dockerfile.fpm
  contrib/docker/php.ini
  contrib/docker/start.sh
  docker-compose.yml
Labels: deployment

#246 Add info about max bio length, make names length customizable
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/SettingsController.php
  config/pixelfed.php
  resources/views/settings/home.blade.php
Labels: enhancement

#321 Expose RSS syndication feeds on profile page via <link href="..." > tags
  resources/views/profile/show.blade.php
Labels: enhancement, ui
