Repository pixelfed/pixelfed, pull requests merged in 2018-12, with the labels that each got.

#628 [WIP] Timeline Refactor
  app/Http/Controllers/Api/BaseApiController.php
  app/Http/Controllers/InternalApiController.php
  app/Http/Controllers/PublicApiController.php
  app/Http/Controllers/SiteController.php
  app/Http/Controllers/TimelineController.php
  app/Profile.php
  app/Transformer/Api/MediaTransformer.php
  app/Transformer/Api/NotificationTransformer.php
  config/pixelfed.php
  package-lock.json
  package.json
  public/js/components.js
  public/mix-manifest.json
  resources/assets/js/components.js
  resources/assets/js/components/PostComponent.vue
  resources/assets/js/components/Timeline.vue
  resources/views/layouts/partial/nav.blade.php
  resources/views/timeline/home.blade.php
  resources/views/timeline/local.blade.php
  routes/web.php
Labels: api, performance, refactoring, ui, work in progress

#662 v0.7.0
  app/Console/Commands/FixUsernames.php
  app/Follower.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/Api/BaseApiController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/AvatarController.php
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/DiscoverController.php
  app/Http/Controllers/FederationController.php
  app/Http/Controllers/SettingsController.php
  app/Jobs/DeletePipeline/DeleteAccountPipeline.php
  app/Listeners/AuthLogin.php
  app/Notification.php
  app/Profile.php
  app/Status.php
  app/Transformer/ActivityPub/Verb/Like.php
  app/User.php
  app/Util/ActivityPub/Helpers.php
  app/Util/ActivityPub/HttpSignature.php
  config/pixelfed.php
  resources/views/layouts/partial/nav.blade.php
  resources/views/profile/partial/private-info.blade.php
  resources/views/profile/partial/user-info.blade.php
  resources/views/settings/home.blade.php
  resources/views/settings/remove/permanent.blade.php
  resources/views/site/help/your-profile.blade.php
  routes/web.php
Labels: work in progress, 🚨priority - critical

#653 L10n: Update Czech translation
  resources/lang/vendor/backup/cs/notifications.php
Labels: localization

#676 [274] Add comment button to comment form where browser has 'Touch' event enabled
  resources/assets/js/components.js
  resources/assets/js/components/PostComponent.vue
  resources/assets/sass/custom.scss
Labels: accessibility, ui
