Repository pixelfed/pixelfed, pull requests merged in 2018-06, with the labels that each got.

#78 Prevent card from stretching on profile page
  resources/assets/sass/custom.scss
Labels: ui

#120 Use route() for settings link
  resources/views/layouts/partial/nav.blade.php
Labels: refactoring

#39 i18n Completes Occitan translation
  resources/lang/oc/notification.php
  resources/lang/oc/profile.php
Labels: internationalization, ui

#66 Always center content without leaking in card
  resources/assets/sass/custom.scss
Labels: ui

#83 Add accept attribute
  resources/views/timeline/personal.blade.php
  resources/views/timeline/public.blade.php
Labels: ui

#91 🌍: 🇵🇱⬆️
  resources/lang/pl/notification.php
  resources/lang/pl/profile.php
  resources/lang/pl/timeline.php
Labels: internationalization, ui

#93 Use inRandomOrder instead of orderByRaw in Discover page
  app/Console/Commands/SeedFollows.php
  app/Http/Controllers/DiscoverController.php
Labels: compatibility

#95 Do not show “Follow” button in notifications if already followed
  resources/views/account/activity.blade.php
Labels: enhancement

#99 updated swedish translation
  resources/lang/sv/notification.php
  resources/lang/sv/profile.php
  resources/lang/sv/timeline.php
Labels: internationalization, ui

#100 Create timeline.php
  resources/lang/es/timeline.php
Labels: internationalization, ui

#101 Token→"token" and one forgotten word to translate
  resources/lang/es/passwords.php
Labels: internationalization, ui

#102 Update profile.php
  resources/lang/es/profile.php
Labels: internationalization, ui

#103 Update notification.php
  resources/lang/es/notification.php
Labels: internationalization, ui

#104 Update auth.php
  resources/lang/sv/auth.php
Labels: internationalization, ui

#109 galician (gl), translating pixelfed beta
  resources/lang/gl/README.md
  resources/lang/gl/auth.php
  resources/lang/gl/notification.php
  resources/lang/gl/pagination.php
  resources/lang/gl/passwords.php
  resources/lang/gl/profile.php
  resources/lang/gl/timeline.php
  resources/lang/gl/validation.php
Labels: internationalization, ui

#126 Japanese translation 🇯🇵
  resources/lang/ja/auth.php
  resources/lang/ja/notification.php
  resources/lang/ja/pagination.php
  resources/lang/ja/passwords.php
  resources/lang/ja/profile.php
  resources/lang/ja/timeline.php
  resources/lang/ja/validation.php
Labels: internationalization, localization

#150 Improve image view
  app/Http/Controllers/StatusController.php
  app/Providers/AppServiceProvider.php
  app/Util/Lexer/PrettyNumber.php
  app/Util/Media/Image.php
  config/pixelfed.php
  resources/assets/sass/custom.scss
  resources/views/status/show.blade.php
  resources/views/timeline/partial/new-form.blade.php
  resources/views/timeline/personal.blade.php
  resources/views/timeline/public.blade.php
Labels: enhancement, ui

#38 Workable Docker container definitions and docker-compose runtime
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: deployment, enhancement

#163 Fix margins on follower/following list
  resources/views/profile/followers.blade.php
  resources/views/profile/following.blade.php
Labels: ui

#198 Relicense from MIT to AGPL
  LICENSE
Labels: legal

#122 Change id to username in users list and change the url
  resources/views/admin/users/home.blade.php
Labels: enhancement, requires in depth, ui

#144 Introduce OpenGraph meta tags
  resources/views/discover/home.blade.php
  resources/views/discover/tags/show.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  resources/views/profile/followers.blade.php
  resources/views/profile/following.blade.php
  resources/views/profile/show.blade.php
  resources/views/site/about.blade.php
  resources/views/site/bannedinstances.blade.php
  resources/views/site/features.blade.php
  resources/views/site/fediverse.blade.php
  resources/views/site/help.blade.php
  resources/views/site/libraries.blade.php
  resources/views/site/opensource.blade.php
  resources/views/site/partial/template.blade.php
  resources/views/site/platform.blade.php
  resources/views/site/privacy.blade.php
  resources/views/site/terms.blade.php
  resources/views/status/show.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#200 Replace to perfect license
  LICENSE
Labels: legal

#147 Add Finnish translations
  resources/lang/fi/auth.php
  resources/lang/fi/notification.php
  resources/lang/fi/pagination.php
  resources/lang/fi/passwords.php
  resources/lang/fi/profile.php
  resources/lang/fi/timeline.php
Labels: internationalization, localization

#165 lowercase name in nodeinfo
  app/Http/Controllers/FederationController.php
Labels: api, bug

#166 Fixed typos.
  resources/lang/sv/auth.php
  resources/lang/sv/validation.php
Labels: internationalization, localization

#173 Add breakpoined border to status view
  resources/assets/sass/custom.scss
  resources/views/status/show.blade.php
Labels: enhancement, ui

#180 New new user profile look
  resources/views/profile/followers.blade.php
  resources/views/profile/following.blade.php
  resources/views/profile/partial/user-info.blade.php
  resources/views/profile/show.blade.php
Labels: enhancement, ui

#183 Update French language timeline.php
  resources/lang/fr/timeline.php
Labels: internationalization, localization

#184 Update French language notification.php
  resources/lang/fr/notification.php
Labels: internationalization, localization

#185 Update French language profile.php
  resources/lang/fr/profile.php
Labels: internationalization, localization

#197 Fixes to look of status view
  resources/assets/sass/custom.scss
  resources/views/status/show.blade.php
Labels: enhancement, ui

#211 Fix missing bootstrap prefix in activity page
  resources/views/account/activity.blade.php
Labels: bug, ui

#219 Fix squashed avatars and long images in timelines
  resources/assets/sass/custom.scss
  resources/views/status/template.blade.php
Labels: ui

#225 Add titles to icons
  resources/views/layouts/partial/nav.blade.php
  resources/views/status/show.blade.php
  resources/views/status/template.blade.php
Labels: accessibility, ui

#239 Fix following/ers page titles
  resources/views/profile/followers.blade.php
  resources/views/profile/following.blade.php
Labels: ui

#260 Hebrew Translation Update
  resources/lang/he/navmenu.php
  resources/lang/he/notification.php
Labels: internationalization, localization

#272 Make icons in status more consistent
  resources/views/status/show.blade.php
  resources/views/status/template.blade.php
Labels: ui

#273 Make mobile cards flush
  resources/views/layouts/partial/nav.blade.php
  resources/views/status/template.blade.php
  resources/views/timeline/partial/new-form.blade.php
  resources/views/timeline/personal.blade.php
  resources/views/timeline/public.blade.php
Labels: ui

#282 Allow setting the locale from environment
  config/app.php
Labels: deployment

#289 Frontend ui refactor
  config/app.php
  public/css/app.css
  public/img/pixelfed-full-color.svg
  public/js/app.js
  public/mix-manifest.json
  resources/assets/js/components/commentform.js
  resources/assets/sass/custom.scss
  resources/lang/de/navmenu.php
  resources/lang/de/notification.php
  resources/lang/en/profile.php
  resources/lang/he/navmenu.php
  resources/lang/he/notification.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/503.blade.php
  resources/views/layouts/partial/nav.blade.php
  resources/views/profile/followers.blade.php
  resources/views/profile/following.blade.php
  resources/views/report/form.blade.php
  resources/views/site/fediverse.blade.php
  resources/views/site/language.blade.php
  resources/views/site/privacy.blade.php
  resources/views/status/show.blade.php
  resources/views/status/template.blade.php
  resources/views/timeline/partial/new-form.blade.php
  resources/views/timeline/personal.blade.php
  resources/views/timeline/public.blade.php
Labels: ui

#298 general: Add detailed README.md
  .env.example
  README.md
Labels: docs
