Repository pixelfed/pixelfed, pull requests merged in 2019-06, with the labels that each got.

#1388 Add Remote Follows
  .env.example
  app/Console/Commands/FixUsernames.php
  app/Console/Commands/Installer.php
  app/Http/Controllers/Admin/AdminSettingsController.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/FollowerController.php
  app/Http/Controllers/Settings/PrivacySettings.php
  app/Http/Controllers/Settings/RelationshipSettings.php
  app/Http/Controllers/SettingsController.php
  app/Jobs/RemoteFollowPipeline/RemoteFollowImportRecent.php
  app/Listeners/AuthLogin.php
  app/Observers/UserObserver.php
  app/Status.php
  app/Util/ActivityPub/Helpers.php
  app/Util/ActivityPub/Validator/UndoFollow.php
  config/federation.php
  database/migrations/2019_06_16_051157_add_profile_ids_to_users_table.php
  package-lock.json
  package.json
  public/css/app.css
  public/css/appdark.css
  public/css/landing.css
  public/js/components.js
  public/js/compose.js
  public/js/profile.js
  public/js/status.js
  public/mix-manifest.json
  resources/assets/js/components/ComposeModal.vue
  resources/assets/js/components/PostComponent.vue
  resources/assets/js/components/Profile.vue
  resources/views/settings/accessibility.blade.php
  resources/views/settings/email.blade.php
  resources/views/settings/home.blade.php
  resources/views/settings/partial/sidebar.blade.php
  resources/views/settings/relationships/home.blade.php
  resources/views/settings/security.blade.php
  resources/views/site/help/your-profile.blade.php
  routes/web.php
  tests/Unit/ActivityPub/FollowTest.php
  tests/Unit/ActivityPub/Verb/AcceptVerbTest.php
  tests/Unit/ActivityPub/Verb/UndoFollowTest.php
  webpack.mix.js
Labels: 💼 WIP, 🕸️ ActivityPub, 🚨 Priority: Critical

#1398 fix #1394
  resources/assets/js/components/SearchResults.vue
Labels: 🐛 Bug, 👀 UI

#1424 Add Contact Form
  app/Contact.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/ContactController.php
  app/Jobs/ContactPipeline/ContactPipeline.php
  config/instance.php
  resources/lang/en/site.php
  resources/views/admin/apps/home.blade.php
  resources/views/admin/home.blade.php
  resources/views/admin/messages/home.blade.php
  resources/views/admin/messages/show.blade.php
  resources/views/admin/partial/topnav.blade.php
  resources/views/layouts/partial/footer.blade.php
  resources/views/site/contact.blade.php
  resources/views/site/partial/sidebar.blade.php
  routes/web.php
Labels: 💼 WIP

#1473 change aspect ratio of status video player
  resources/assets/js/components/presenter/VideoPresenter.vue
Labels: 👀 UI

#1474 allow post-component to shrink to fit media
  resources/assets/js/components/PostComponent.vue
Labels: 👀 UI
