Repository pixelfed/pixelfed, pull requests merged in 2019-08, with the labels that each got.

#1587 Update nginx.conf
  contrib/nginx.conf
Labels: ⚙️ Deployment

#1602 Allow redis to be used over a UNIX socket
  .env.example
  .env.testing
  config/cache.php
  config/database.php
Labels: ⚙️ Deployment, ➕Enhancement

#1626 Fix queue bug
  app/Console/Commands/CatchUnoptimizedMedia.php
  app/Http/Controllers/Api/AdminApiController.php
  app/Http/Controllers/Api/BaseApiController.php
  app/Http/Controllers/ApiController.php
  app/Http/Controllers/InternalApiController.php
  app/Transformer/Api/StatusTransformer.php
Labels: ❗❗ Priority: High, 💼 WIP, 🕸️ ActivityPub, 🧠 Backend
