Repository pixelfed/pixelfed, pull requests merged in 2019-03, with the labels that each got.

#913 Don't show “load more” if there is nothing more to load
  resources/assets/js/components/Profile.vue
  resources/assets/js/components/Timeline.vue
Labels: enhancement, ui

#936 Add zh-tw translations.
  resources/lang/zh-tw/auth.php
  resources/lang/zh-tw/navmenu.php
  resources/lang/zh-tw/notification.php
  resources/lang/zh-tw/pagination.php
  resources/lang/zh-tw/passwords.php
  resources/lang/zh-tw/profile.php
  resources/lang/zh-tw/site.php
  resources/lang/zh-tw/timeline.php
  resources/lang/zh-tw/validation.php
Labels: 🌐 Localization

#1005 Update Japanese translation file
  resources/lang/ja/navmenu.php
  resources/lang/ja/notification.php
  resources/lang/ja/profile.php
  resources/lang/ja/site.php
Labels: 🌐 Localization

#1010 L10n: Update Czech translation 🇨🇿
  resources/lang/cs/navmenu.php
  resources/lang/cs/notification.php
  resources/lang/cs/profile.php
  resources/lang/cs/site.php
Labels: 🌐 Localization

#1011 Portuguese translation
  resources/lang/pt/auth.php
  resources/lang/pt/navmenu.php
  resources/lang/pt/notification.php
  resources/lang/pt/pagination.php
  resources/lang/pt/passwords.php
  resources/lang/pt/profile.php
  resources/lang/pt/site.php
  resources/lang/pt/timeline.php
  resources/lang/pt/validation.php
Labels: 🌐 Localization

#1015 Shrink mobile gutters
  resources/assets/js/components/Timeline.vue
Labels: ➕Enhancement, 👀 UI

#1016 Fix incorrect break points
  resources/assets/js/components/Timeline.vue
Labels: 🐛 Bug, 👀 UI

#1027 Added an env var in the Dockerfile
  contrib/docker/Dockerfile.apache
Labels: ⚙️ Deployment

#1050 L10n: Update Czech translation 🇨🇿
  resources/lang/cs/helpcenter.php
Labels: 🌐 Localization

#1061 Add apple-touch-icon to blade templates
  resources/views/layouts/anon.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/blank.blade.php
  resources/views/layouts/bundle.blade.php
  resources/views/site/index.blade.php
Labels: 🔧 Compatibility

#1063 Use button element
  resources/assets/js/components/PostComponent.vue
  resources/assets/js/components/Timeline.vue
  resources/assets/sass/custom.scss
Labels: 👁️ Accessibility

#1065 fix button styling
  resources/assets/js/components/PostComponent.vue
  resources/assets/js/components/Timeline.vue
  resources/assets/sass/custom.scss
Labels: 🐛 Bug, 👀 UI

#1067 actually fix apple mobile icon
  resources/views/layouts/anon.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/blank.blade.php
  resources/views/layouts/bundle.blade.php
  resources/views/site/index.blade.php
Labels: 🔧 Compatibility
