Repository pixelfed/pixelfed, pull requests merged in 2019-09, with the labels that each got.

#1661 use fa-stack for admin badge
  resources/assets/js/components/Profile.vue
Labels: 🐛 Bug, 👀 UI

#1708 v0.10.4
  .env.example
  CHANGELOG.md
  app/Http/Controllers/Api/ApiV1Controller.php
  app/Http/Controllers/Api/BaseApiController.php
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/FederationController.php
  app/Http/Controllers/FollowerController.php
  app/Http/Controllers/PublicApiController.php
  app/Http/Controllers/Settings/HomeSettings.php
  app/Http/Controllers/SiteController.php
  app/Listeners/AuthLogin.php
  app/Providers/AuthServiceProvider.php
  app/Transformer/Api/AccountTransformer.php
  app/Transformer/Api/NotificationTransformer.php
  database/migrations/2019_09_21_015556_add_language_to_users_table.php
  public/img/pixelfed-icon-color.png
  public/js/activity.js
  public/js/collectioncompose.js
  public/js/collections.js
  public/js/compose-classic.js
  public/js/compose.js
  public/js/profile.js
  public/js/status.js
  public/js/timeline.js
  public/mix-manifest.json
  resources/assets/js/components/Activity.vue
  resources/assets/js/components/CollectionComponent.vue
  resources/assets/js/components/CollectionCompose.vue
  resources/assets/js/components/ComposeClassic.vue
  resources/assets/js/components/ComposeModal.vue
  resources/assets/js/components/NotificationCard.vue
  resources/assets/js/components/PostComponent.vue
  resources/assets/js/components/Profile.vue
  resources/assets/js/components/Timeline.vue
  resources/lang/cy/auth.php
  resources/lang/cy/helpcenter.php
  resources/lang/cy/navmenu.php
  resources/lang/cy/notification.php
  resources/lang/cy/pagination.php
  resources/lang/cy/passwords.php
  resources/lang/cy/profile.php
  resources/lang/cy/site.php
  resources/lang/cy/timeline.php
  resources/lang/cy/validation.php
  resources/views/settings/home.blade.php
  resources/views/site/language.blade.php
  resources/views/site/privacy.blade.php
  resources/views/site/terms.blade.php
  resources/views/status/comments.blade.php
  routes/api.php
  routes/web.php
Labels: 💼 WIP

#1715 Use correct ID when Accepting an activity
  app/Util/ActivityPub/Inbox.php
Labels: 🕸️ ActivityPub, 🧠 Backend
