Repository pixelfed/pixelfed, pull requests merged in 2019-02, with the labels that each got.

#768 Make NSFW shade the same size as its container
  resources/assets/sass/custom.scss
Labels: enhancement, ui

#782 Update Hebrew translation
  resources/lang/he/profile.php
  resources/lang/he/site.php
Labels: localization

#834 Add database indexes for objects using soft delete
  database/migrations/2019_02_13_221138_add_soft_delete_indexes.php
Labels: performance

#850 Status transform cache
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/LikeController.php
  app/Http/Controllers/StatusController.php
  app/Transformer/Api/StatusTransformer.php
Labels: performance

#848 Speed up docker build times and decrease image size
  contrib/docker/Dockerfile.fpm
Labels: deployment

#859 Turkish translation
  resources/lang/tr/auth.php
  resources/lang/tr/navmenu.php
  resources/lang/tr/notification.php
  resources/lang/tr/pagination.php
  resources/lang/tr/passwords.php
  resources/lang/tr/profile.php
  resources/lang/tr/site.php
  resources/lang/tr/timeline.php
  resources/lang/tr/validation.php
Labels: localization

#861 L10n: Update Czech translation
  resources/lang/cs/notification.php
  resources/lang/cs/passwords.php
Labels: localization

#899 Update Indonesian translation
  resources/lang/id/auth.php
  resources/lang/id/profile.php
  resources/lang/id/validation.php
Labels: localization

#860 Fix open collective URL
  package.json
Labels: typo

#905 i18n: 🇵🇱
  resources/lang/pl/navmenu.php
  resources/lang/pl/notification.php
  resources/lang/pl/passwords.php
  resources/lang/pl/profile.php
  resources/lang/pl/site.php
Labels: localization
