Repository pixelfed/pixelfed, pull requests merged in 2019-01, with the labels that each got.

#767 [764] output media caption to activitypub objects
  app/Transformer/ActivityPub/StatusTransformer.php
Labels: accessibility, activitypub

#701 Add required PHP extensions to composer.json
  composer.json
Labels: deployment

#724 [598] Apply content-box box-sizing to avatars images
  resources/assets/sass/custom.scss
  resources/views/status/reply.blade.php
Labels: bug, ui

#725 L10n: Update Czech translation
  resources/lang/cs/profile.php
Labels: localization

#731 add default ACTIVITY_PUB=false to .env.example
  .env.example
Labels: activitypub, deployment
