Repository pixelfed/pixelfed, pull requests merged in 2019-05, with the labels that each got.

#1234 fix info overlay on small layouts
  resources/assets/sass/custom.scss
Labels: 🐛 Bug, 👀 UI

#1236 fix moment ui container sizing
  resources/assets/js/components/Profile.vue
Labels: 🐛 Bug, 👀 UI

#1238 Add drop-shadow to next/prev arrows
  resources/assets/sass/custom.scss
Labels: 👀 UI, 🖐️ UX

#1239 fit image to filter preview
  resources/assets/sass/custom.scss
Labels: 👀 UI

#1259 add doubletap to like
  package-lock.json
  package.json
  resources/assets/js/components.js
  resources/assets/js/components/PostComponent.vue
  resources/assets/js/components/Profile.vue
  resources/assets/js/components/Timeline.vue
Labels: 👀 UI, 🖐️ UX, 🤔 In-Depth
