Repository pixelfed/pixelfed, pull requests merged in 2019-04, with the labels that each got.

#1101 PostComponent refactor
  app/Http/Controllers/PublicApiController.php
  app/Http/Controllers/StatusController.php
  app/Jobs/CommentPipeline/CommentPipeline.php
  app/Transformer/Api/StatusTransformer.php
  app/Util/ActivityPub/Helpers.php
  resources/assets/js/components.js
  resources/assets/js/components/PostComments.vue
  resources/assets/js/components/PostMenu.vue
  resources/assets/js/components/presenter/PhotoAlbumPresenter.vue
  resources/assets/js/components/presenter/PhotoPresenter.vue
  resources/assets/js/profile.js
  resources/assets/js/status.js
  resources/assets/js/timeline.js
Labels: 👀 UI, 💼 WIP, 🕸️ ActivityPub, 🖐️ UX

#1109 [docker] Build and install php-intl in Dockerfile.apache.
  contrib/docker/Dockerfile.apache
Labels: ⚙️ Deployment

#1110 Add vertical margin to profile timeline view
  resources/assets/js/components/Profile.vue
Labels: 👀 UI

#1155 Add ext-intl requirement
  composer.json
Labels: ⚙️ Deployment

#1145 [WIP] Docker support with pgsql/sqlite3 and fixed en_US locales.
  .env.example
  contrib/docker/Dockerfile.apache
  contrib/docker/Dockerfile.fpm
  contrib/docker/start.sh
  docker-compose.yml
Labels: ⚙️ Deployment

#1184 Docker patch 2
  .env.example
  contrib/docker/Dockerfile.apache
  contrib/docker/start.sh
  docker-compose.yml
Labels: ⚙️ Deployment

#1203 Override font-weight-lighter to 300
  resources/assets/sass/_variables.scss
  resources/assets/sass/custom.scss
Labels: 👀 UI, 👁️ Accessibility

#1218 fix white block in dark moment ui
  resources/assets/js/components/PostComponent.vue
Labels: 👀 UI
